- name: Open required ports
  firewalld:
    immediate: yes
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  loop:
    - 6443
    - 2379
    - 2380
    - 10250
    - 10251
    - 10252
#- name: Initialize Kubernetes master node
#  command: kubeadm init --apiserver-advertise-address=192.168.150.2 --pod-network-cidr=10.244.0.0/16
- name: Create .kube directory for vagrant user
  file:
    path: /home/vagrant/.kube
    state: directory
  become_user: vagrant
- name: Copy kubectl configuration informations for vagrant user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
- name: Set permission of local kubernetes configuration
  file:
    path: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
- name: Install a POD network add-on (flannel)
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml
- name: Taint master node to accept pods
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
- name: Save join token in the common shared directory
  shell: kubeadm token create --print-join-command > /vagrant/join.sh
- name: Install the Kubernetes Dashboard
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml
- name: Publish the Kubernetes Dashboard
  command: kubectl apply -f /tmp/kubernetes-dashboard-public.yml
